// <auto-generated />
namespace ScheduleTravel.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class update_TourSchedule_SortByday : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(update_TourSchedule_SortByday));
        
        string IMigrationMetadata.Id
        {
            get { return "201910160102132_update_TourSchedule_SortByday"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
